- src/integ-test/bdd-test/features/primitives/verifyPaymentNotice_semantic_ko.feature
- src/integ-test/bdd-test/features/primitives/verifyPaymentNotice_semantic_ok.feature
Some fixes to scenarios
- Scenario: Check outcome OK if combination psp-channel-pa in denylist
- Scenario: Check PPT_DOMINIO_SCONOSCIUTO error on non-existent pa
- Scenario: Check PPT_DOMINIO_DISABILITATO error on disabled pa
> [PAG-1101] scenarios fixes

- src/integ-test/bdd-test/features/primitives/verificaBollettino_syntax_ko.feature
- src/integ-test/bdd-test/features/steps/steps.py
> verificaBollettinoReq_TestSintattici_ko

- src/integ-test/bdd-test/features/primitives/activatePaymentNotice_syntax_ko.feature
- src/integ-test/bdd-test/features/steps/steps.py
Syntax tests for activatePaymentNoticeReq with KO outcome
> activatePaymentNotice_syntax_ko.feature

- src/integ-test/bdd-test/features/primitives/nodoVerificaRPT_semantic_ko.feature
- src/integ-test/bdd-test/features/primitives/verificaBollettino_syntax_ko.feature
> fix-run-test

- src/integ-test/bdd-test/features/steps/steps.py
- src/integ-test/bdd-test/features/steps/utils.py
> fixed code with outcome KO

- src/integ-test/bdd-test/features/primitives/verificaBollettino_semantic_ko.feature
- src/integ-test/bdd-test/features/primitives/verificaBollettino_semantici_ko.feature
- src/integ-test/bdd-test/features/steps/steps.py
> verificaBollettinoReq_semantic_ko

- src/integ-test/bdd-test/features/environment.py
- src/integ-test/bdd-test/features/primitives/verificaBollettino_semantic_ko.feature
- src/integ-test/bdd-test/features/primitives/verificaBollettino_semantic_ok.feature
- src/integ-test/bdd-test/resources/config.json
> [PAG-1140] verificaBollettinoReq_semantici_ok

- docs/behave-report.html
- src/integ-test/bdd-test/features/flows/activatePaymentNotice_process_ko.feature
process check for activatePaymentNotice - KO from PA [PRO_APNR_06]
> [PAG-1136] activatePaymentNotice_process_ko

- src/integ-test/bdd-test/features/primitives/activatePaymentNotice_semantic_ko.feature
Semantic tests for activatePaymentNoticeReq with KO outcome
> [PAG-1135] activatePaymentNotice_semantic_ko.feature

- src/integ-test/bdd-test/features/primitives/activatePaymentNotice_semantic_ok.feature
- src/integ-test/bdd-test/features/steps/steps.py
Semantic tests for activatePaymentNoticeReq with OK outcome
> [PAG-1135] activatePaymentNotice_semantic_ok.feature

- src/integ-test/bdd-test/features/flows/paGetPayment_pspNotifyPayment_sendPaymentOutcome.feature
- src/integ-test/bdd-test/features/flows/paVerifyPaymentNoticeRes_syntax_ko.feature
- src/integ-test/bdd-test/features/primitives/activatePaymentNotice_semantic_ko.feature
- src/integ-test/bdd-test/features/primitives/activatePaymentNotice_semantic_ok.feature
- src/integ-test/bdd-test/features/primitives/activatePaymentNotice_syntax_ok.feature
- src/integ-test/bdd-test/features/steps/steps.py
Restored code lost during previous merge and rebase 🐛
> Restored code

- src/integ-test/bdd-test/features/flows/activatePaymentNoticeReq_payment_PAID_activate_blocco_02.feature
- src/integ-test/bdd-test/features/flows/paGetPayment_pspNotifyPayment_sendPaymentOutcome.feature
- src/integ-test/bdd-test/features/steps/steps.py
block check for activatePaymentNoticeReq - position status in PAID [Activate_blocco_02]
> activatePaymentNoticeReq_blocco_02

- src/integ-test/bdd-test/features/flows/activatePaymentNoticeReq_payment_NOTIFIED_activate_blocco_03.feature
- src/integ-test/bdd-test/features/flows/activatePaymentNoticeReq_payment_PAID_activate_blocco_02.feature
block check for activatePaymentNoticeReq - position status in NOTIFIED [Activate_blocco_03]
> activatePaymentNoticeReq_blocco_03

- src/integ-test/bdd-test/features/flows/activatePaymentNotice_semantic_with_useIdempotency_ko.feature
> [PAG-1138] activate payment notice req idempotency semantic err

- src/integ-test/bdd-test/features/flows/verificaBollettino_flow.feature
- src/integ-test/bdd-test/features/steps/steps.py
> verificaBollettino_flow

- src/integ-test/bdd-test/features/primitives/paGetPaymentRes_syntax_ko.feature
- src/integ-test/bdd-test/features/steps/utils.py
> Pag-1168 paGetPaymentRes - Test sintattici ko

- src/integ-test/bdd-test/features/flows/sendPaymentOutcome_semantic_STATO_PAID_PPT_PAGAMENTO_DUPLICATO.feature
- src/integ-test/bdd-test/features/flows/sendPaymentOutcome_semantic_STATO_PAYNG_PPT_PAGAMENTO_DUPLICATO.feature
> [PAG-1165] sendPaymentOutcome_semantic_STATO_PAYING-duplicato

- src/integ-test/bdd-test/features/primitives/paGetPaymentRes_semantic_ko.feature
> Pag-1169-paGetPaymentRes - Test semantici  ko

- .gitignore
- src/integ-test/bdd-test/features/primitives/paGetPaymentRes_semantic_ok.feature
- src/integ-test/bdd-test/features/steps/steps.py
> Pag-1169-paGetPaymentRes - Test semantici ok

- src/integ-test/bdd-test/features/flows/sendPaymentOutcome_semantic_outcome_ko.feature
> [PAG-1165] sendPaymentOutcome_semantic_outcome_ko

- src/integ-test/bdd-test/features/primitives/sendPaymentOutcome_semantic_ok.feature
> [PAG-1165] sendPaymentOutcome_semantic_ok

- src/integ-test/bdd-test/features/flows/sendPaymentOutcome_semantic_without_useIdempotency.feature
> PAG-1167-sendPaymentOutcome-idempotency-not-useIdemp-

- src/integ-test/bdd-test/features/flows/sendPaymentOutcome_semantic_with_useIdempotency_cache_clean.feature
- src/integ-test/bdd-test/features/steps/steps.py
> PAG-1167-sendPaymentOutcome-idempotency-useIdemp-cacheClean

- src/integ-test/bdd-test/features/flows/sendPaymentOutcome_semantic_with_useIdempotency_ko.feature
- src/integ-test/bdd-test/features/steps/steps.py
- src/integ-test/bdd-test/features/steps/utils.py
> PAG-1167-sendPaymentOutcome-idempotency-useIdemp-ko

- .devops/code-review-pipelines.yml
The purpose of this PR is to run test automatically on every new pr to add or update test on nodo-dei-pagamenti
> [PPR-292] upd CI pipeline

- src/integ-test/bdd-test/features/flows/sendPaymentOutcome_semantic_PPT_TOKEN_SCONOSCIUTO.feature
> [PAG-1165] sendPaymentOutcome_PPT_TOKEN_SCONOSCIUTO

- src/integ-test/bdd-test/features/flows/sendPaymentOutcome_semantic_PPT_PAGAMENTO_SCONOSCIUTO.feature
- src/integ-test/bdd-test/features/steps/steps.py
> [PAG-1165] sendPaymentOutcome_PPT_PAGAMENTO_SCONOSCIUTO

- src/integ-test/bdd-test/features/environment.py
- src/integ-test/bdd-test/features/steps/steps.py
- src/integ-test/bdd-test/features/steps/utils.py
Added mapping of primitive to service to be invoked.
According to Azure configuration each primitive should call a specific node service. 
For local configuration is maintained `soap_service` attribute as field of `config.json`.
> [PPR-307] Primitive mapping

- .devops/code-review-pipelines.yml
Added date to the title of report.
- changed code-review pipeline to add date automatically after test execution
> [PPR-308] Added date to title

- .devops/code-review-pipelines.yml
> Fix code-review pipeline

- src/integ-test/bdd-test/features/primitives/pspNotifyPaymentReq_syntax_paypal.feature
- src/integ-test/bdd-test/features/steps/steps.py
- src/integ-test/bdd-test/features/steps/utils.py
> pspNotifyPayment_syntax_paypal

- src/integ-test/bdd-test/features/primitives/pspNotifyPaymentReq_syntax_carte.feature
> pspNotifyPayment_syntax_carte

- src/integ-test/bdd-test/features/primitives/pspNotifyPaymentReq_semantic_paypal.feature
- src/integ-test/bdd-test/features/steps/steps.py
> pspNotifyPayment_semantic_paypal

- src/integ-test/bdd-test/features/flows/pspNotifyPaymentResponse_process_pspIrraggiungibile.feature
> [PAG-1212] pspNotifyPayment_process_pspIrraggiungibile

- .github/workflows/check_metadata_pr.yml
add a new action to check the size of the PR
> feat : Add New GH Action PR Label Size

- .azuredevops/pipeline-restart-sit-mock.yml
> added mock restart pipeline
